### ISSUE TITLE
Pulse Eight CEC adapter + windows 10 + sony 43 x800D standby mode kicks in no matter what?

### ISSUE THREAD

**Issue by markm75** [Pulse-Eight/cec-dotnet#4]
I decided to give the pulse eight cec adapter a shot, so that it could automatically turn off the 43" uhd after it hit the windows idle time.. it worked out well even in 4k 60 RGB mode (but you need premium monoprice cables and set to blanking mode in the custom resolutions to work correctly).

The issue is... even with windows set to NO standby.. if you run the software for this cec device, it will shut off into standby the pc after so many mins, no matter what.. ie: set screen to go off in 3 minutes, the whole pc is usually in stand by in 30.

If i kill the libCEC v3 or v4 software and test, it doesnt enter standby..

Has anyone used this adapter and ran into this?

Thanks in advance

**Comment by opdenkamp** [comment]
Sorry for the late response, but I haven't seen this while testing the latest changes on Windows. It might have been solved already, but not been released yet.

Which software are you using? Are you using Kodi, cec-tray, or something else?

**Comment by markm75** [comment]
Hi there

 

I’m on windows 10 x64 creators edition using the cec-tray app.. not using kodi, just straight windows.. if you leave the tray app open, set windows to say timeout after 3 minutes.. within 20 or so the whole pc hits standby mode, even if standby is disabled.. also.. if you just hit power on the remote to the tv, it shuts it off but then sets whole pc to standby mode.

 

It would be nice to get around this.. even if remote desktoped to the pc, it will timeout if tray icon is running and kick into standby on its own (so for now I disable cec-tray if I’m doing sensitive things that I don’t want kicked out of due to standby)

 

Mark

**Comment by opdenkamp** [comment]
That's the same Windows version that I was using for testing this, but I've only checked the other applications and haven't looked at cec-tray much yet. There's another, similar, issue with the fake sleep/wake mode that I'll look into once the release for the main libCEC is finished.

edit: away mode is what they call it :) https://github.com/Pulse-Eight/cec-dotnet/issues/2

**Comment by markm75** [comment]
Just curious if there's an update on this yet. I still see the same version 
under downloads though

Thanks

**Comment by opdenkamp** [comment]
This should be resolved in the current cec-dotnet. When the TV sends a CEC standby (including pressing power on the TV remote), cec-tray suspends the PC as before, but this is now controllable via the **Suspend the PC when the TV is turned off** option (`global_stop_tv_standby`) on the Power Control tab. Uncheck it and the PC will no longer go to standby when the TV does.

It's left enabled by default, since suspending along with the TV is what most setups expect, but it's now a single checkbox to turn off.

The related "away mode" behaviour mentioned above (#2) has also been implemented since. Closing as fixed — please reopen if you still see the PC suspending with that option disabled.

**Comment by markm75** [comment]
How do you update the cec-dot net to test this? it seems to be source code only?
